default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  username: <%= ENV.fetch('DB_USERNAME', 'keslleycapelin') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'uuwqbr70') %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: inss_discount_development

test:
  <<: *default
  database: inss_discount_test

production:
  <<: *default
  database: inss_discount_production
  username: inss_discount
  password: <%= ENV["INSS_DISCOUNT_DATABASE_PASSWORD"] %>
